// Generated by scripts/recovery/generate-shims.mjs. A compat shim is correct when every old name IS the owner's export.
import test from "node:test";
import assert from "node:assert/strict";
import * as shim0 from "../dist/index.js";
import * as owner0 from "obix-binding-jsx";
import * as shim1 from "../dist/primitives.js";
import * as owner1 from "obix-binding-jsx";
import * as shim2 from "../dist/forms.js";
import * as owner2 from "obix-binding-jsx";
import * as shim3 from "../dist/navigation.js";
import * as owner3 from "obix-binding-jsx";
import * as shim4 from "../dist/overlays.js";
import * as owner4 from "obix-binding-jsx";
import * as shim5 from "../dist/feedback.js";
import * as owner5 from "obix-binding-jsx";
import * as shim6 from "../dist/controls.js";
import * as owner6 from "obix-binding-jsx";
import * as shim7 from "../dist/data.js";
import * as owner7 from "obix-binding-jsx";
import * as shim8 from "../dist/search.js";
import * as owner8 from "obix-binding-jsx";

test("obix-jsx-components: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim0["obixAccordion"], owner0["obixAccordion"], "obixAccordion");
  assert.equal(shim0["obixAlert"], owner0["obixAlert"], "obixAlert");
  assert.equal(shim0["obixAutocomplete"], owner0["obixAutocomplete"], "obixAutocomplete");
  assert.equal(shim0["obixBreadcrumb"], owner0["obixBreadcrumb"], "obixBreadcrumb");
  assert.equal(shim0["obixButton"], owner0["obixButton"], "obixButton");
  assert.equal(shim0["obixCard"], owner0["obixCard"], "obixCard");
  assert.equal(shim0["obixCheckbox"], owner0["obixCheckbox"], "obixCheckbox");
  assert.equal(shim0["obixDatePicker"], owner0["obixDatePicker"], "obixDatePicker");
  assert.equal(shim0["obixDropdown"], owner0["obixDropdown"], "obixDropdown");
  assert.equal(shim0["obixFileUpload"], owner0["obixFileUpload"], "obixFileUpload");
  assert.equal(shim0["obixForm"], owner0["obixForm"], "obixForm");
  assert.equal(shim0["obixImage"], owner0["obixImage"], "obixImage");
  assert.equal(shim0["obixInput"], owner0["obixInput"], "obixInput");
  assert.equal(shim0["obixLink"], owner0["obixLink"], "obixLink");
  assert.equal(shim0["obixLoading"], owner0["obixLoading"], "obixLoading");
  assert.equal(shim0["obixModal"], owner0["obixModal"], "obixModal");
  assert.equal(shim0["obixNavigation"], owner0["obixNavigation"], "obixNavigation");
  assert.equal(shim0["obixPagination"], owner0["obixPagination"], "obixPagination");
  assert.equal(shim0["obixProgress"], owner0["obixProgress"], "obixProgress");
  assert.equal(shim0["obixRadioGroup"], owner0["obixRadioGroup"], "obixRadioGroup");
  assert.equal(shim0["obixSearch"], owner0["obixSearch"], "obixSearch");
  assert.equal(shim0["obixSelect"], owner0["obixSelect"], "obixSelect");
  assert.equal(shim0["obixSlider"], owner0["obixSlider"], "obixSlider");
  assert.equal(shim0["obixStepper"], owner0["obixStepper"], "obixStepper");
  assert.equal(shim0["obixSwitch"], owner0["obixSwitch"], "obixSwitch");
  assert.equal(shim0["obixTable"], owner0["obixTable"], "obixTable");
  assert.equal(shim0["obixTabs"], owner0["obixTabs"], "obixTabs");
  assert.equal(shim0["obixTextarea"], owner0["obixTextarea"], "obixTextarea");
  assert.equal(shim0["obixToast"], owner0["obixToast"], "obixToast");
  assert.equal(shim0["obixTooltip"], owner0["obixTooltip"], "obixTooltip");
  assert.equal(shim0["obixVideo"], owner0["obixVideo"], "obixVideo");
  assert.deepEqual(Object.keys(shim0).sort(), ["obixAccordion","obixAlert","obixAutocomplete","obixBreadcrumb","obixButton","obixCard","obixCheckbox","obixDatePicker","obixDropdown","obixFileUpload","obixForm","obixImage","obixInput","obixLink","obixLoading","obixModal","obixNavigation","obixPagination","obixProgress","obixRadioGroup","obixSearch","obixSelect","obixSlider","obixStepper","obixSwitch","obixTable","obixTabs","obixTextarea","obixToast","obixTooltip","obixVideo"]);
});

test("obix-jsx-components/primitives: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim1["obixButton"], owner1["obixButton"], "obixButton");
  assert.equal(shim1["obixCard"], owner1["obixCard"], "obixCard");
  assert.equal(shim1["obixImage"], owner1["obixImage"], "obixImage");
  assert.equal(shim1["obixLink"], owner1["obixLink"], "obixLink");
  assert.equal(shim1["obixVideo"], owner1["obixVideo"], "obixVideo");
  assert.deepEqual(Object.keys(shim1).sort(), ["obixButton","obixCard","obixImage","obixLink","obixVideo"]);
});

test("obix-jsx-components/forms: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim2["obixCheckbox"], owner2["obixCheckbox"], "obixCheckbox");
  assert.equal(shim2["obixDatePicker"], owner2["obixDatePicker"], "obixDatePicker");
  assert.equal(shim2["obixFileUpload"], owner2["obixFileUpload"], "obixFileUpload");
  assert.equal(shim2["obixForm"], owner2["obixForm"], "obixForm");
  assert.equal(shim2["obixInput"], owner2["obixInput"], "obixInput");
  assert.equal(shim2["obixRadioGroup"], owner2["obixRadioGroup"], "obixRadioGroup");
  assert.equal(shim2["obixSelect"], owner2["obixSelect"], "obixSelect");
  assert.equal(shim2["obixTextarea"], owner2["obixTextarea"], "obixTextarea");
  assert.deepEqual(Object.keys(shim2).sort(), ["obixCheckbox","obixDatePicker","obixFileUpload","obixForm","obixInput","obixRadioGroup","obixSelect","obixTextarea"]);
});

test("obix-jsx-components/navigation: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim3["obixBreadcrumb"], owner3["obixBreadcrumb"], "obixBreadcrumb");
  assert.equal(shim3["obixNavigation"], owner3["obixNavigation"], "obixNavigation");
  assert.equal(shim3["obixPagination"], owner3["obixPagination"], "obixPagination");
  assert.equal(shim3["obixStepper"], owner3["obixStepper"], "obixStepper");
  assert.equal(shim3["obixTabs"], owner3["obixTabs"], "obixTabs");
  assert.deepEqual(Object.keys(shim3).sort(), ["obixBreadcrumb","obixNavigation","obixPagination","obixStepper","obixTabs"]);
});

test("obix-jsx-components/overlays: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim4["obixDropdown"], owner4["obixDropdown"], "obixDropdown");
  assert.equal(shim4["obixModal"], owner4["obixModal"], "obixModal");
  assert.equal(shim4["obixTooltip"], owner4["obixTooltip"], "obixTooltip");
  assert.deepEqual(Object.keys(shim4).sort(), ["obixDropdown","obixModal","obixTooltip"]);
});

test("obix-jsx-components/feedback: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim5["obixAlert"], owner5["obixAlert"], "obixAlert");
  assert.equal(shim5["obixLoading"], owner5["obixLoading"], "obixLoading");
  assert.equal(shim5["obixProgress"], owner5["obixProgress"], "obixProgress");
  assert.equal(shim5["obixToast"], owner5["obixToast"], "obixToast");
  assert.deepEqual(Object.keys(shim5).sort(), ["obixAlert","obixLoading","obixProgress","obixToast"]);
});

test("obix-jsx-components/controls: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim6["obixSlider"], owner6["obixSlider"], "obixSlider");
  assert.equal(shim6["obixSwitch"], owner6["obixSwitch"], "obixSwitch");
  assert.deepEqual(Object.keys(shim6).sort(), ["obixSlider","obixSwitch"]);
});

test("obix-jsx-components/data: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim7["obixAccordion"], owner7["obixAccordion"], "obixAccordion");
  assert.equal(shim7["obixTable"], owner7["obixTable"], "obixTable");
  assert.deepEqual(Object.keys(shim7).sort(), ["obixAccordion","obixTable"]);
});

test("obix-jsx-components/search: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim8["obixAutocomplete"], owner8["obixAutocomplete"], "obixAutocomplete");
  assert.equal(shim8["obixSearch"], owner8["obixSearch"], "obixSearch");
  assert.deepEqual(Object.keys(shim8).sort(), ["obixAutocomplete","obixSearch"]);
});
