// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { obixSlider, obixSwitch } from "obix-binding-jsx";
export type { ObixSliderProps, ObixSwitchProps } from "obix-binding-jsx";
