// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { obixAccordion, obixTable } from "obix-binding-jsx";
export type { ObixAccordionProps, ObixTableProps } from "obix-binding-jsx";
