// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { obixAlert, obixLoading, obixProgress, obixToast } from "obix-binding-jsx";
export type { ObixAlertProps, ObixLoadingProps, ObixProgressProps, ObixToastProps } from "obix-binding-jsx";
