// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { obixCheckbox, obixDatePicker, obixFileUpload, obixForm, obixInput, obixRadioGroup, obixSelect, obixTextarea } from "obix-binding-jsx";
export type { ObixCheckboxProps, ObixDatePickerProps, ObixFileUploadProps, ObixFormProps, ObixInputProps, ObixRadioGroupProps, ObixSelectProps, ObixTextareaProps } from "obix-binding-jsx";
