// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { obixBreadcrumb, obixNavigation, obixPagination, obixStepper, obixTabs } from "obix-binding-jsx";
export type { ObixBreadcrumbProps, ObixNavigationProps, ObixPaginationProps, ObixStepperProps, ObixTabsProps } from "obix-binding-jsx";
