// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { obixDropdown, obixModal, obixTooltip } from "obix-binding-jsx";
export type { ObixDropdownProps, ObixModalProps, ObixTooltipProps } from "obix-binding-jsx";
