// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { obixButton, obixCard, obixImage, obixLink, obixVideo } from "obix-binding-jsx";
export type { ObixButtonProps, ObixCardProps, ObixImageProps, ObixLinkProps, ObixVideoProps } from "obix-binding-jsx";
