// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { obixAutocomplete, obixSearch } from "obix-binding-jsx";
export type { ObixAutocompleteProps, ObixSearchProps } from "obix-binding-jsx";
